### ISSUE TITLE
Creating a Serverless R Shiny App using Quarto with R Shinylive 

### ISSUE THREAD

**Issue by dmresearch15** [coatless-quarto/r-shinylive-demo#10]
I've followed  [TheCoatlessProfessor](https://www.youtube.com/watch?v=6y2FnAugP8E) and using the steps the following files are created (please see attached file).

But it didn't create shinylivedemo-sw.js. Any idea why. I am using RStudio on Windows 10.
![Capture](https://github.com/coatless-quarto/r-shinylive-demo/assets/14191012/0d4b0527-ad0c-4649-922d-0e5b6411d14e)

**Comment by coatless** [comment]
No file was attached. What is inside of `shinylivedemo_files`?

**Comment by coatless** [comment]
What is the content in `shinylivedemo.qmd`?

**Comment by dmresearch15** [comment]
Inside of shinylivedemo_file:

```
 shinylivedemo_file\libs, 
 shinylivedemo_file\libs\bootstrap, 
 shinylivedemo_file\libs\clipboard, 
 shinylivedemo_file\libs\quarto-html
```

Attached: shinylivedemo.qmd (Note: As per your demo,I was putting in shinylivedemo-sw.js in the header but could not locate in \shinylivedemo directory. So I could not proceed.

shinylivedemo.qmd is below:

````md
---
title: "shinylivedemo"
format:
  html:
    grid:
      body-width: 1400px
    resources:
      - shinylivedemo-sw.js
filters: 
  - shinylive
---

```         
#| standalone: true
#| viewerHeight: 600
library(shiny)
library(bslib)

theme <- bs_theme(font_scale = 1.5)

# Define UI for app that draws a histogram ----
ui <- page_sidebar(theme = theme,
  sidebar = sidebar(open = "open",
    numericInput("n", "Sample count", 100),
    checkboxInput("pause", "Pause", FALSE),
  ),
  plotOutput("plot", width=1100)
)

server <- function(input, output, session) {
  data <- reactive({
    input$resample
    if (!isTRUE(input$pause)) {
      invalidateLater(1000)
    }
    rnorm(input$n)
  })
  
  output$plot <- renderPlot({
    hist(data(),
      breaks = 40,
      xlim = c(-2, 2),
      ylim = c(0, 1),
      lty = "blank",
      xlab = "value",
      freq = FALSE,
      main = ""
    )
    
    x <- seq(from = -2, to = 2, length.out = 500)
    y <- dnorm(x)
    lines(x, y, lwd=1.5)
    
    lwd <- 5
    abline(v=0, col="red", lwd=lwd, lty=2)
    abline(v=mean(data()), col="blue", lwd=lwd, lty=1)

    legend(legend = c("Normal", "Mean", "Sample mean"),
      col = c("black", "red", "blue"),
      lty = c(1, 2, 1),
      lwd = c(1, lwd, lwd),
      x = 1,
      y = 0.9
    )
  }, res=140)
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

````

**Note:** Edit by @coatless was applied to fix formatting, e.g. using:

`````md
````md

# example

````
`````

**Comment by coatless** [comment]
`shinylivedemo.qmd` is missing the code cell engine for shinylive denoted with:

````md
```{shinylive-r}

```
````

Please add it. e.g.

````md
---
title: "shinylivedemo"
format:
  html:
    grid:
      body-width: 1400px
    resources:
      - shinylivedemo-sw.js
filters: 
  - shinylive
---

Added the code engine... 

```{shinylive-r}
#| standalone: true
#| viewerHeight: 600
library(shiny)
library(bslib)

## Suppressed UI/Server

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```
````

c.f. https://github.com/coatless-quarto/r-shinylive-demo?tab=readme-ov-file#including-the-shiny-app-in-your-quarto-document

**Comment by dmresearch15** [comment]
Thank you. It is working now.

Can you give me an idea please what are the files I can share with my colleagues so they can view the app without R and R server?

**Comment by coatless** [comment]
See deploying the app here:

https://github.com/coatless-quarto/r-shinylive-demo?tab=readme-ov-file#publishing-your-quarto-document

For CI, you can see the deployment workflow being used on this tutorial here:

https://github.com/coatless-quarto/r-shinylive-demo?tab=readme-ov-file#advanced-optional-step-continuous-publishing-using-github-actions 

For details on deploying outside of using GH Pages, please see:

https://quarto-webr.thecoatlessprofessor.com/qwebr-troubleshooting.html#directly-accessing-rendered-html

**Comment by dmresearch15** [comment]
Appreciate the materials provided for app deployment!
