### ISSUE TITLE
Support for Quarto Shiny dashboards

### ISSUE THREAD

**Issue by bisacciamd** [coatless-quarto/r-shinylive-demo#11]
In recent months there's been significant development in [Quarto Dashboards](https://quarto.org/docs/dashboards/), and [Shinylive integration in Quarto](https://github.com/coatless-quarto/r-shinylive-demo). However, at present, it is not possible to integrate Shinylive specifically within a Quarto Dashboard running a Shiny application. 

As Quarto dashboards use a somewhat similar structure to standard Shiny apps, I think integration of this feature in Shinylive would be feasible & extend Shinylive applicability and use cases.

**Comment by coatless** [comment]
> [!NOTE]
> 
> Some background for the googler, this is related to a question @bisacciamd asked on StackOverflow and ended up in my inbox, which was redirected here. The relevant SO question:
> 
> **A way for shinylive integration for serverless Quarto R Dashboard?**
> https://stackoverflow.com/q/78073680/20898996?sem=2 

@bisacciamd This repository is related to a tutorial using Shinylive within Quarto. The issue ticket you typed up is more of a feature request for the Shinylive for R project. I would suggest placing the request at either:

- Quarto Shinylive Extension: https://github.com/quarto-ext/shinylive/issues/
- R shinylive package to export pre-existing apps:  https://github.com/posit-dev/r-shinylive/issues/

In the interim, I probably would encourage you to set up a Shiny App that uses the `{bslib}` library to deliver a shiny dashboard:

https://rstudio.github.io/bslib/articles/dashboards/index.html

For instance, consider the following `myapp/app.R`:

```r
library(shiny)
library(bslib)

ui <- page_sidebar(
  title = "My dashboard",
  sidebar = "Sidebar",
  "Main content area"
)

server <- function(input, output) {
  # code here
}

shinyApp(ui, server)
```

This would allow you to then directly convert the shiny app to shinylive via:

```r
# Install shinylive from CRAN
install.packages("shinylive")

# Convert the shiny app in `myapp` to a shinylive app available in `site/`
shinylive::export("myapp", "site")

# Check locally the dashboard
httpuv::runStaticServer("site/")
```

Publish the `site/` files on GitHub pages to fully get a working app. I'll probably throw together a quick deployment guide based on the above skeleton later tonight.

**Comment by coatless** [comment]
@bisacciamd sorry for the delay; it's been hectic. 

So, I've ported over the example Earthquake dashboard that Quarto Dashboard used to a Shiny Dashboard powered by bslib. From there, I've converted it into an r shinylive dashboard app. 

You can see the repository over here: 

https://github.com/coatless-tutorials/r-shinylive-dashboard-app

The app should appear here (warning, large file size on mobile): 

https://tutorials.thecoatlessprofessor.com/r-shinylive-dashboard-app/

**Comment by bisacciamd** [comment]
Wow - thank you very much @coatless, this is impressive — I'll look into it and try my luck. 

BW
