### ISSUE TITLE
Error: Specifier not found in cache

### ISSUE THREAD

**Issue by durraniu** [coatless-quarto/r-shinylive-demo#14]
Thanks for creating this demo. I am on Windows 10. I cloned your repo and tried rendering the `index.qmd` and `R-shinylive-demo.qmd` files after installing the `shinylive` package. But I get the following output with an error. Could you help me finding out what's wrong?
```
==> quarto preview index.qmd --to html --no-watch-inputs --no-browse

pandoc 
  to: html
  output-file: index.html
  standalone: true
  title-prefix: r-shinylive in Quarto
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  toc: true
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  grid:
    body-width: 1300px
    sidebar-width: 200px
    margin-width: 200px
  title: R-shinylive app in Quarto!
  resources:
    - shinylive-sw.js
  
error: Specifier not found in cache: "https://deno.land/std/io/mod.ts", --cached-only is specified.
    at file:///C:/Users/umair/AppData/Local/shinylive/shinylive/Cache/shinylive-0.5.0/scripts/codeblock-to-json.js:5:27
Error running filter C:/Users/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:
Error running quarto (error code 1): <no output>
stack traceback:
	...live-demo\_extensions\quarto-ext\shinylive\shinylive.lua:417: in function <...live-demo\_extensions\quarto-ext\shinylive\shinylive.lua:398>
	[C]: in ?
	[C]: in method 'walk'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:558: in local 'checked_walk'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1335: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1389: in function <...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1386>
stack traceback:
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:558: in local 'checked_walk'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:610: in function 'run_emulated_filter'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1335: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1351: in upvalue 'run_emulated_filter_chain'
	...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1389: in function <...s/umair/AppData/Local/Apps/Quarto/share/filters/main.lua:1386>
```

**Comment by coatless** [comment]
I can't reproduce this on my end with material posted as-is in the repository.

<img width="1493" alt="Screenshot of the page working fine under local source" src="https://github.com/user-attachments/assets/9d69fdb5-33a6-43c7-bc50-e5ce511085b8">

I would suggest making sure that you are: 

1. up-to-date with the version of R present
   - This should be R 4.4.1 or R 4.4.2
2. using the R shinylive package on CRAN. 

```r
install.packages("shinylive")
```

3. Running Quarto v1.5.57
    - **Note:** if you have an outdated copy of RStudio, this may be problematic.

In the Terminal tab within RStudio, type: 

```sh
quarto check
```

You should get:

```sh
Quarto 1.5.57
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.57
      Path: /Applications/quarto/bin
....
```

**Comment by durraniu** [comment]
My R version is 4.3.2 so that may be the culprit. The remaining requirements are okay, i.e., shinylive is installed and quarto version is 1.6.32.
Thank you for the help. I am closing the issue.

**Comment by coatless** [comment]
@durraniu there's a lot of instability in the latest preview release of Quarto (v1.6.32)

https://github.com/quarto-dev/quarto-cli/discussions/10951

I would suggest downgrading. The error is suggesting a deno issue, which might have crept back in.

**Comment by durraniu** [comment]
Thanks for pointing that out. I'll try upgrading R and downgrading quarto and report back.

**Comment by durraniu** [comment]
Update: With R 4.4.2 and Quarto 1.5.57, the app works! Thank you.

**Comment by coatless** [comment]
@durraniu great to hear. FYI, this is a known issue with Quarto v1.6 pre-release due to a change in how deno imports need to occur. Details: https://prerelease.quarto.org/docs/projects/scripts.html#deno-scripts


The issue is already being tracked at the appropriate repository:  

https://github.com/quarto-ext/shinylive/issues/65
https://github.com/posit-dev/shinylive/issues/185

The only downside is if you need to use `{quarto-shinylive}` extension, you can't use it with a pre-release!
