### ISSUE TITLE
How to show the app code along with the app in shinylive?

### ISSUE THREAD

**Issue by durraniu** [coatless-quarto/r-shinylive-demo#6]
Thank you for providing this demo. Really useful! 

I was wondering if it is possible to show the code alongside the app? Similar to the `display.mode = "showcase"` option in `runApp()`? I tried it in the `shinylive-r` chunk but the app did not render.

**Comment by coatless** [comment]
There isn't a display mode available for `shinylive` (R or Python versions) right now. 

That said, there are a couple of options:

1. Have an "active" `shinylive-r` cell followed immediately by inactive `r` cells.
2. Link out to the Shinylive for R Editor or App viewer

## Option 1: Copy and Paste

For the first, we can show the app code just by copying and pasting and, then, placing it immediately under the active area. For example: 

````md

Here's my shinylive app! 

```{shinylive-r}
#| label: fig-shiny-demo-app
#| viewerHeight: 505
#| standalone: true
library(shiny)

# Define UI for app ---
ui <- fluidPage(
  h1("Hello there!")
)

# Define server logic ----
server <- function(input, output) {
  # logic
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

This is a verbatim copy of the code running above: 

```{r}
library(shiny)

# Define UI for app ---
ui <- fluidPage(
  h1("Hello there!")
)

# Define server logic ----
server <- function(input, output) {
  # logic
}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```

````


## Option 2: Link out to Shinylive Editor 

Another alternative is using the Shinylive Editor to show the code alongside the working code. 
Specifically, we can use the editor at:

https://shinylive.io/r/editor

Fill it with our code 

<img width="932" alt="Shinylive Editor for R filled with code" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/833642/ad1c0907-14ca-4705-8383-b5e35239c1ab">

Then, select the share button in the upper right corner: 

<img width="222" alt="Select share code area" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/833642/9a853390-8d01-462a-8213-3e1bbdff4689">

By clicking the copy URL next to editor: 

<img width="701" alt="Obtain URL with webcode link" src="https://github.com/coatless-quarto/r-shinylive-demo/assets/833642/cf61eed3-ee57-4281-8152-d3da2bb40dac">

This would generate the following link: 

https://shinylive.io/r/editor/#code=NobwRAdghgtgpmAXGKAHVA6ASmANGAYwHsIAXOMpMAGwEsAjAJykYE8AKAZwAtaJWAlAB0IIgMQACACJwAZnzgSAqgEkJsoowlpUEgLQGRAV1oSAPHvXUTAEwAKUAOZx2IiRO4BGV2AAScamoiCVJuOEY4AEIhMGEIOPFpOQUJTnCAN3CJIMdaAn0DPRE0xkytC3UjCAJSWhJ2PlQjUlwJImam0gEJEDcJSRy8kQBfEUSAYQiocgkAZV5+bXQCwwgePlYAQXR2EwkAXgkTVpKyg9SM8IEwYYBdIA

The link can be placed under your app if needed.

**Comment by durraniu** [comment]
Thanks for the suggestions.

**Comment by coatless** [comment]
@durraniu; actually, I take that back. We can embed the editor and app view into the Quarto without needing to go out to the editor website by using inside the chunk:

````
```{shinylive-r}
#| standalone: true
#| components: [editor, viewer]

# app code from above
```
````

Example:


<img width="1520" alt="Demo of Shinylive R app showing the editor alongside viewer components." src="https://github.com/coatless-quarto/r-shinylive-demo/assets/833642/e86f2c80-35d1-456a-9ca7-1d07a72e11b9">
