### ISSUE TITLE
Shinylive in posts

### ISSUE THREAD

**Issue by xl0418** [coatless-quarto/r-shinylive-demo#7]
Hi, thanks for the great demo! I managed to reproduce it following your demo.

I wonder if I can have this feature for every posts in a Blog? Do I need to install the extensions for every posts? Thanks!

**Comment by coatless** [comment]
Yup, just add the extension in the main quarto project directory (e.g. next to `_quarto.yml`). Then, within the `_quarto.yml`, add the following:

```yml
# Enable the shinylive filter globally
filters:
  - shinylive
```

This will cause shinylive to be applied to each post.

**Comment by xl0418** [comment]
Thanks! Got it!
