### ISSUE TITLE
How to run the app after creation?

### ISSUE THREAD

**Issue by dmresearch15** [coatless-quarto/r-shinylive-demo#9]
Thanks for your work and it is nice.

I've successfully created an app in a local drive \app1.

Now I can run this app using httpuv::runStaticServer("\\app1") in R.

Now what should I do so others can view it without R and R server.

**Comment by coatless** [comment]
@dmresearch15 this sounds like a standalone shinylive app instead of a quarto webpage. The main way of achieving this goal would be to push the shinylive files onto GitHub Pages and, then, share the link.
